jclw<>qu Wl:g># plyx.f>qh.#l:g>#.Wl:g>#
jclw<>qu khu_f>m>q_sq>w_nhb plyx.vulmr.khu_f>m>q_sq>w_nhb
jclw<>qu >r >r

jcrhu BLUE_A (.79, .69, .59, .3)
jcrhu BLUE (.79, .69, .59,)
jcrhu RED (.3, .6, .6, .3)
jcrhu YELLOW (617/699, 642/699, 69/699)
jcrhu WHITE (7,7,7,.3)
jcrhu BLUE_GREY khu_f>m>q_sq>w_nhb("j624643")
jcrhu @vhqxrlah (mdwegd bc b ls Wl:g>#.#lgunz958 hmrh b+48)
jcrhu <dvrh "\vF4E1"
jcrhu <dvrh_>fudk>: "\vF4E0"